// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLEsCSpQhwpBI6miXwNmdFoB72kDzls5Y',
    appId: '1:445734744510:web:f2574c44f4df3171de49ef',
    messagingSenderId: '445734744510',
    projectId: 'shifabook-4ebe0',
    authDomain: 'shifabook-4ebe0.firebaseapp.com',
    storageBucket: 'shifabook-4ebe0.appspot.com',
    measurementId: 'G-6EMTK4SGY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrq33RvRmwFEPZ5uBWH6pjrwmvOWYiiqU',
    appId: '1:445734744510:android:b17fe0e32be13b3ade49ef',
    messagingSenderId: '445734744510',
    projectId: 'shifabook-4ebe0',
    storageBucket: 'shifabook-4ebe0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlz2ko5wOtGDPNmSePmyd8EXr3kpImmrs',
    appId: '1:445734744510:ios:ce77d4885c5ef6b5de49ef',
    messagingSenderId: '445734744510',
    projectId: 'shifabook-4ebe0',
    storageBucket: 'shifabook-4ebe0.appspot.com',
    iosBundleId: 'com.example.shifabook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlz2ko5wOtGDPNmSePmyd8EXr3kpImmrs',
    appId: '1:445734744510:ios:ce77d4885c5ef6b5de49ef',
    messagingSenderId: '445734744510',
    projectId: 'shifabook-4ebe0',
    storageBucket: 'shifabook-4ebe0.appspot.com',
    iosBundleId: 'com.example.shifabook',
  );
}
